# Generated by Django 3.0.5 on 2020-10-13 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Digitalizador',
            fields=[
                ('idDigitalizador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('idEstado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('Folio', models.IntegerField(primary_key=True, serialize=False)),
                ('tomos', models.CharField(max_length=100)),
                ('oficios', models.CharField(max_length=10)),
                ('referencia', models.CharField(max_length=10)),
                ('idEstado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('noPaquete', models.IntegerField(primary_key=True, serialize=False)),
                ('folioInicio', models.IntegerField()),
                ('folioFin', models.IntegerField()),
                ('fechaExp', models.DateField()),
                ('noFojas', models.IntegerField()),
                ('recepcion', models.IntegerField()),
                ('validacion', models.IntegerField()),
                ('sellado', models.IntegerField()),
                ('cosido', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Preparador',
            fields=[
                ('idPreparador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Verificador',
            fields=[
                ('idVerificador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='preparador',
            name='idVerificador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Verificador'),
        ),
    ]
