# Generated by Django 3.0.5 on 2020-10-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201013_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='fechaRealizado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='folio',
            name='tomos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='cosido',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='noFojas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='recepcion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='sellado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='validacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
